version: '3.8'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  celery_worker:
    build: .
    command: celery -A apps worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery_beat:
    build: .
    command: celery -A apps beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
