# Generated by Django 4.2.1 on 2023-09-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("themind", "0002_rename_value_randomnumber_value1_randomnumber_value2"),
    ]

    operations = [
        migrations.AddField(
            model_name="randomnumber",
            name="room_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
