# Generated by Django 4.2.1 on 2023-09-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("themind", "0003_randomnumber_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="randomnumber",
            name="user_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="randomnumber",
            name="room_name",
            field=models.CharField(max_length=50),
        ),
    ]
