# Generated by Django 4.2.1 on 2023-05-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tailorscoop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Today",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=8096)),
                ("timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "today",
                "ordering": ["timestamp"],
            },
        ),
    ]
