# Generated by Django 4.2.1 on 2023-05-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tailorscoop", "0002_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscription",
            name="hashed_email",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
