# Generated by Django 4.2.1 on 2023-05-12 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tailorscoop", "0003_newslettersubscription_hashed_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("hashed_email", models.CharField(max_length=255)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
